export const author: UserI = {
  id: "110",
  name: "Bilal Shah",
  email: "bilalshah.dev@gmail.com",
  bio: "Experienced full stack developer proficient in MERN stack, Next.js, TypeScript, Tailwind CSS, shadcn/ui, PostgreSQL, and Git.",
  city: "Islamabad",
  country: "Pakistan",
  website: "https://bilalhassan.netlify.app/",
  createdAt: new Date("2023-05-26"),
};

export const randomUsers: UserI[] = [
  {
    id: "101",
    name: "Alice Johnson",
    email: "alice@example.com",
    bio: "Passionate about web development and design.",
    city: "New York",
    country: "USA",
    website: "https://alicejohnson.com/",
    createdAt: new Date("2022-10-15"),
  },
  {
    id: "102",
    name: "John Doe",
    email: "john.doe@example.com",
    bio: "Software engineer with expertise in backend development.",
    city: "San Francisco",
    country: "USA",
    website: "https://johndoe.dev/",
    createdAt: new Date("2022-09-20"),
  },
  {
    id: "103",
    name: "Emma Smith",
    email: "emma.smith@example.com",
    bio: "Frontend developer specializing in React and Vue.js.",
    city: "London",
    country: "UK",
    website: "https://emmasmith.co.uk/",
    createdAt: new Date("2022-11-30"),
  },
  {
    id: "104",
    name: "David Brown",
    email: "david@example.com",
    bio: "Passionate about open-source software and contributing to the community.",
    city: "Berlin",
    country: "Germany",
    website: "https://davidbrown.org/",
    createdAt: new Date("2023-01-10"),
  },
  {
    id: "105",
    name: "Sophia Garcia",
    email: "sophia@example.com",
    bio: "UI/UX designer with a focus on creating beautiful and intuitive user interfaces.",
    city: "Paris",
    country: "France",
    website: "https://sophiagarcia.design/",
    createdAt: new Date("2023-02-28"),
  },
];
